Repository marlon360/rki-covid-api, pull requests merged in 2020-10, with the labels that each got.

#4 Add lastUpdate, weekDifference and weekIncidence and fix death count and names
  .gitignore
  api/states.ts
  model.ts
Labels: bug, enhancement

#8 Add map endpoints for states and districts
  README.md
  api/districts-map.ts
  api/states-map.ts
  media/districts-map.png
  media/states-map.png
  package-lock.json
  package.json
Labels: enhancement

#10 Add districts api
  README.md
  api/districts.ts
  api/states.ts
  index.html
  models.ts
Labels: enhancement

#11 add district type to distinguish between 'Landkreis' and 'Kreisfreie Stadt'
  README.md
  api/districts.ts
  models.ts
Labels: hacktoberfest-accepted

#13 Add legend to states and districts map (closes #12)
  api/districts-map.ts
  api/states-map.ts
Labels: enhancement, hacktoberfest-accepted
