Repository marlon360/rki-covid-api, pull requests merged in 2021-04, with the labels that each got.

#180 Add endpoint /testing/history
  README.md
  docs/.vuepress/config.js
  docs/endpoints/testing.md
  docs/index.md
  src/data-requests/testing.ts
  src/responses/testing.ts
  src/server.ts
Labels: enhancement

#183 Fix link in testing.md
  docs/endpoints/testing.md
Labels: bug

#174 New project for project showcase
  README.md
  docs/index.md
Labels: project

#194 Add Janssen vaccine to vaccination.ts and vaccination.md
  docs/endpoints/vaccinations.md
  src/data-requests/vaccination.ts
Labels: bug

#191 Corrected typo
  docs/endpoints/vaccinations.md
Labels: documentation

#199 use consistent style guide in this project
  .github/workflows/code_style.yml
  .github/workflows/docker.yml
  .prettierignore
  README.md
  docker-compose.prod.yaml
  docker-compose.yaml
  docs/.vuepress/config.js
  docs/endpoints/districts.md
  docs/endpoints/germany.md
  docs/endpoints/maps.md
  docs/endpoints/states.md
  docs/endpoints/testing.md
  docs/endpoints/vaccinations.md
  docs/index.md
  package-lock.json
  package.json
  src/configuration/colors.ts
  src/data-requests/districts.ts
  src/data-requests/germany.ts
  src/data-requests/r-value.ts
  src/data-requests/response-data.ts
  src/data-requests/states.ts
  src/data-requests/testing.ts
  src/data-requests/vaccination.ts
  src/responses/districts.ts
  src/responses/germany.ts
  src/responses/map.ts
  src/responses/meta.ts
  src/responses/states.ts
  src/responses/testing.ts
  src/responses/vaccination.ts
  src/server.ts
  src/static/index.html
  src/utils.ts
  tsconfig.json
  vercel.json
Labels: enhancement
