Repository marlon360/rki-covid-api, pull requests merged in 2021-11, with the labels that each got.

#314 Add a legend to the maps
  docs/endpoints/maps.md
  src/configuration/colors.ts
  src/responses/map.ts
  src/server.ts
Labels: enhancement

#317 fix maps with legend on selfhosted api
  docker/Dockerfile
Labels: bug

#246 Add ImpfPush project
  README.md
  docs/index.md
Labels: project

#330 add frozen incidence to germany and states
  docs/endpoints/germany.md
  docs/endpoints/states.md
  src/data-requests/frozen-incidence.ts
  src/responses/germany.ts
  src/responses/map.ts
  src/responses/states.ts
  src/server.ts
  src/utils.ts
Labels: enhancement

#333 Add hospitalization history
  docs/endpoints/germany.md
  docs/endpoints/states.md
  src/responses/germany.ts
  src/responses/states.ts
  src/server.ts
Labels: enhancement

#337 Add hospitalization map
  docs/endpoints/maps.md
  src/configuration/colors.ts
  src/responses/map.ts
  src/server.ts
Labels: enhancement

#347 fix frozen-incidence
  src/data-requests/frozen-incidence.ts
Labels: bug

#344 add Projekt: Corona Ampel Bayern
  README.md
  docs/index.md
Labels: project

#348 Fix frozen incidence 2
  src/data-requests/frozen-incidence.ts
Labels: bug
